// Starts a local Vite server. PLAYWRIGHT_MODULE can point to another Playwright install.
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.TEST_URL || 'http://127.0.0.1:5173'
const fixture = n => fileURLToPath(new URL(`./fixtures/CmMgr-${n}`,import.meta.url))
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5173'],{cwd:fileURLToPath(new URL('../',import.meta.url)),stdio:'pipe'})
server.stderr.on('data',d=>process.stderr.write(d))
process.on('exit',()=>server.kill())
for(let i=0;i<50;i++){try { await fetch(base); break }catch{await new Promise(r=>setTimeout(r,100))}}
const browser=await chromium.launch({headless:true,args:['--no-sandbox']})
const context=await browser.newContext({viewport:{width:1500,height:1100},acceptDownloads:true})
const page=await context.newPage(), errors=[]
page.on('pageerror',e=>errors.push(e.message))
await page.goto(base)
await page.getByRole('combobox',{name:'Active game'}).selectOption('legacy')
await page.locator('.zone input').setInputFiles(fixture('first'))
await page.getByRole('button',{name:'Squad planning & depth',exact:true}).waitFor()
// Header/body cells must share exactly the same column geometry, even on wide tables.
async function checkAlignment() {
 const failures=await page.locator('table.tbl').evaluateAll(tables=>tables.flatMap(t=>{
   const head=[...t.querySelectorAll('thead tr:first-child th')];
   const row=[...t.querySelectorAll('tbody tr')].find(r=>r.children.length===head.length);
   if(!row) return [];
   return head.flatMap((h,i)=>{const a=h.getBoundingClientRect(), b=row.children[i].getBoundingClientRect();return Math.abs(a.x-b.x)>1 || Math.abs(a.width-b.width)>1 ? [`Column ${i} misaligned`] : []})
 })); assert.deepEqual(failures,[])
}
await checkAlignment()
await page.getByRole('button',{name:'Youth (2)',exact:true}).click()
await page.getByRole('heading',{name:'Youth academy',exact:true}).waitFor()
assert.match(await page.locator('main').innerText(),/Youth Fixture/)
assert.match(await page.locator('main').innerText(),/Youth #113/)
assert.match(await page.locator('main').innerText(),/Test Scout/)
await page.getByRole('button',{name:'Squad planning & depth',exact:true}).click()
await page.locator('.pitch-slot').first().waitFor()
assert.equal(await page.locator('.pitch-slot').count(),11)
const xi=await page.locator('.pitch-slot button b').allTextContents()
assert.equal(new Set(xi).size,xi.length)
assert.match(await page.locator('.needs').innerText(),/Senior Fixture/)
await page.screenshot({path:fileURLToPath(new URL('./planning-qa.png',import.meta.url)),fullPage:true})
await page.getByRole('button',{name:'Player search',exact:true}).click()
await page.locator('select').first().selectOption('ST')
await page.getByLabel('Club role').selectOption('backup')
assert.match(await page.locator('tbody').innerText(),/Backup Fixture/)
assert.match(await page.locator('tbody').innerText(),/Senior Fixture · 91/)
assert.doesNotMatch(await page.locator('tbody').innerText(),/Youth Fixture/)
await page.getByRole('button',{name:'Add Backup Fixture to shortlist',exact:true}).click()
await page.getByRole('button',{name:'Shortlist (1)',exact:true}).waitFor()
await page.getByRole('button',{name:'Open another save',exact:true}).click()
await page.locator('.zone input').setInputFiles(fixture('later'))
await page.getByRole('button',{name:'Shortlist (1)',exact:true}).click()
await page.getByRole('button',{name:'Timeline',exact:true}).click()
await page.locator('.timeline-chart circle').nth(1).waitFor()
assert.equal(await page.locator('.timeline-chart circle').count(),2)
assert.match(await page.locator('main').innerText(),/81 → 84/)
assert.match(await page.locator('main').innerText(),/Example FC → Rival FC/)
await page.getByRole('button',{name:'Estimated value',exact:true}).click()
await page.screenshot({path:fileURLToPath(new URL('./timeline-qa.png',import.meta.url)),fullPage:true})
await page.getByRole('button',{name:'Games & saves',exact:true}).click()
const downloadPromise=page.waitForEvent('download')
await page.getByRole('button',{name:'Export entire game',exact:true}).click()
const download=await downloadPromise
const exportPath=await download.path()
await page.getByLabel('Import game').setInputFiles(exportPath)
await page.getByRole('combobox',{name:'Active game'}).waitFor()
await page.waitForFunction(()=>document.querySelector('select[aria-label="Active game"]')?.selectedOptions[0]?.textContent.includes('(imported)'))
await page.getByRole('button',{name:'Load save',exact:true}).first().waitFor()
assert.equal(await page.getByRole('button',{name:'Load save',exact:true}).count(),2)
await page.getByRole('button',{name:'Load save',exact:true}).first().click()
await page.getByRole('button',{name:'Shortlist (1)',exact:true}).waitFor()
await page.getByRole('button',{name:'Shortlist (1)',exact:true}).click()
assert.match(await page.locator('main').innerText(),/81 → 84/)
await page.getByRole('button',{name:'Games & saves',exact:true}).click()
await page.getByRole('button',{name:'Load save',exact:true}).last().click()
await page.getByRole('button',{name:'Shortlist (1)',exact:true}).waitFor()
await page.getByRole('button',{name:'Games & saves',exact:true}).click()
await page.getByRole('button',{name:'Load save',exact:true}).first().waitFor()
assert.equal(await page.getByRole('button',{name:'Load save',exact:true}).count(),2,'Reopening does not duplicate snapshots')
await page.getByRole('textbox',{name:'New game name'}).fill('Separate career')
await page.getByRole('button',{name:'Create game',exact:true}).click()
await page.locator('.zone input').setInputFiles(fixture('first'))
await page.getByRole('button',{name:'Shortlist (0)',exact:true}).waitFor()
await page.getByRole('button',{name:'Games & saves',exact:true}).click()
await page.getByRole('button',{name:'Load save',exact:true}).first().waitFor()
assert.equal(await page.getByRole('button',{name:'Load save',exact:true}).count(),1)
// Check real IndexedDB semantics and pure planner edge cases in the browser.
const checks=await page.evaluate(async()=>{
 const db=await import('/src/snapshots.ts'), planning=await import('/src/planning.ts')
 const p=(id,ovr,positions)=>({id,ovr,pot:ovr,positions,age:25})
 const xi=planning.assignXI([p(1,95,['ST','CM']),p(2,80,['ST'])],['ST','CM'])
 if(xi[0]?.id!==2 || xi[1]?.id!==1) throw Error('Multi-position assignment leaves an avoidable gap')
 const tied=planning.depthRank(new Map([['1:ST',[p(1,90,['ST']),p(2,90,['ST'])]]]),{...p(2,90,['ST']),teamId:1},'ST')
 if(tied.rank!==1) throw Error('OVR ties misclassified')
 const games=await db.listGames(), legacy=games.find(g=>g.id==='legacy'), snaps=await db.allSnapshots('legacy')
 const original=await db.getSavedFile(snaps[0].id)
 const imported=games.find(g=>g.name.endsWith('(imported)')), importedSnaps=await db.allSnapshots(imported.id)
 const restored=await db.getSavedFile(importedSnaps[0].id)
 if(new Uint8Array(original.data).toString()!==new Uint8Array(restored.data).toString()) throw Error('Export roundtrip changed original save bytes')
 const before=games.length
 try { await db.importGame(JSON.stringify({format:'fc26-companion-game',version:1,game:legacy,snapshots:[{id:'broken'}],files:[]})); throw Error('Accepted malformed export') } catch(e) { if(e.message==='Accepted malformed export') throw e }
 if((await db.listGames()).length!==before) throw Error('Invalid import mutated games')
 await db.toggleTarget(legacy.id,9999); await db.toggleTarget(legacy.id,9999)
 if((await db.listGames()).find(g=>g.id===legacy.id).shortlist.includes(9999)) throw Error('Toggle not committed')
 await db.deleteSnapshot(importedSnaps[0].id)
 if(await db.getSavedFile(importedSnaps[0].id)) throw Error('Snapshot delete left its raw save')
 return {games:games.length,planner:'unique optimal assignment',roundtrip:'byte-exact',invalidImport:'atomic rejection',delete:'snapshot and file removed'}
})
await page.getByRole('button',{name:'Player search',exact:true}).click()
await page.getByLabel('Search position').selectOption('CM')
await page.getByLabel('Club role').selectOption('buried')
await page.getByRole('button',{name:'Add ThirdCM Fixture to shortlist',exact:true}).waitFor()
const cmRows=page.locator('tbody tr')
assert.equal(await cmRows.count(),1)
assert.match(await cmRows.innerText(),/Neves Fixture/)
assert.match(await cmRows.innerText(),/Vitinha Fixture/)
assert.match(await cmRows.innerText(),/2 starting slots/)
await checkAlignment()
await page.screenshot({path:fileURLToPath(new URL('./search-alignment-qa.png',import.meta.url)),fullPage:true})
await page.getByLabel('Search position').selectOption('RM')
await page.getByLabel('Club role').selectOption('all')
assert.equal(await page.locator('tbody tr').count(),1)
assert.doesNotMatch(await page.locator('tbody').innerText(),/Palmer/)
await page.getByLabel('Club role').selectOption('backup')
assert.equal(await page.locator('tbody tr').count(),0)
await page.getByLabel('Position matching').selectOption('all')
await page.getByRole('button',{name:'Add Estevao Fixture to shortlist',exact:true}).waitFor()
assert.match(await page.locator('tbody').innerText(),/Palmer Fixture/)
await page.setViewportSize({width:700,height:1000})
await checkAlignment()
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)
assert.equal(overflow,false,'Tables must scroll internally on narrow screens')
assert.deepEqual(errors,[])
console.log(JSON.stringify({status:'PASS',checks},null,2))
await browser.close()
server.kill()
